### ISSUE TITLE
The cli crashes when adding a DNS entry

### ISSUE THREAD

**Issue by daviddutch** [exoscale/cli#117]
The cli crashes when adding a DNS entry when I execute this command:
`$ exo dns add A mydomain.com -a ${DEPLOYMENT_SERVER_IP} -n ${MACHINE_NAME}`

I get the following error:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6a9689]

goroutine 1 [running]:
github.com/exoscale/egoscale.(*Client).dnsRequest(0x0, 0xe81c00, 0xc0001b9680, 0xc000501ac0, 0x16, 0x0, 0x0, 0x0, 0xc93196, 0x3, ...)
	/src/vendor/github.com/exoscale/egoscale/dns.go:314 +0x59
github.com/exoscale/egoscale.(*Client).GetDomain(0x0, 0xe81c00, 0xc0001b9680, 0x7ffd4db36741, 0xa, 0x0, 0x0, 0xc000501ba0)
	/src/vendor/github.com/exoscale/egoscale/dns.go:157 +0xd4
github.com/exoscale/cli/cmd.glob..func12(0x13d0e80, 0xc0005612c0, 0x1, 0x5, 0x0, 0x0)
	/src/cmd/dns_records_add.go:35 +0x19b
github.com/spf13/cobra.(*Command).execute(0x13d0e80, 0xc000561270, 0x5, 0x5, 0x13d0e80, 0xc000561270)
	/src/vendor/github.com/spf13/cobra/command.go:762 +0x473
github.com/spf13/cobra.(*Command).ExecuteC(0x13d7e20, 0x20, 0xc000000300, 0xaf252d)
	/src/vendor/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0x13d7e20, 0xd2e8d8, 0xc000219e00)
	/src/vendor/github.com/spf13/cobra/command.go:800 +0x2b
github.com/exoscale/cli/cmd.Execute(0xe5ed10, 0x5, 0xe7d000, 0x28)
	/src/cmd/root.go:92 +0x1c2
main.main()
	/src/main.go:34 +0x5e
```

My CLI is running in a docker container and configured with ENV variables. Other commands such as vm list and create work fine.

**Comment by pierre-emmanuelJ** [comment]
Hello 😄 I have just fixed this issue in this commit https://github.com/exoscale/cli/commit/caaa0c323c51678f55c41d90f668e77f0094719b
Thanks a lot for your issue reporting  🚀

**Comment by daviddutch** [comment]
Hi, thanks for the fast fix.
When is the next release planned?

**Comment by greut** [comment]
@daviddutch sorry for the delay, pulling v1.1.3 should hopefully fix your issue. Many thanks for the reports. :clap:
