### ISSUE TITLE
"exo sos create" with non-existent zone hangs

### ISSUE THREAD

**Issue by hansmi** [exoscale/cli#177]
When given a non-existing zone (e.g. a typo) the `exo sos create` command never finishes. It doesn't handle ^C either and needs SIGQUIT via ^4.

```
$ exo sos create -z doesnotexist test
^\SIGQUIT: quit
PC=0x45a3d1 m=0 sigcode=128

goroutine 0 [idle]:
runtime.futex(0x1561168, 0x80, 0x0, 0x0, 0x0, 0x7ffd00000000, 0x0, 0x0, 0x7ffd354e4420, 0x40a201, ...)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/sys_linux_amd64.s:535 +0x21
runtime.futexsleep(0x1561168, 0x7ffd00000000, 0xffffffffffffffff)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/os_linux.go:46 +0x4b
runtime.notesleep(0x1561168)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/lock_futex.go:151 +0xa1
runtime.stoplockedm()
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:2076 +0x8c
runtime.schedule()
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:2477 +0x3ba
runtime.park_m(0xc00006c600)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:2605 +0xa1
runtime.mcall(0x0)   
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/asm_amd64.s:299 +0x5b

goroutine 1 [chan receive]:
github.com/minio/minio-go/v6.Client.executeMethod(0xc000326180, 0xc000328360, 0x1, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0004eb770, 0xc0001ffea0, ...)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/minio/minio-go/v6/api.go:586 +0x4e9
github.com/minio/minio-go/v6.Client.MakeBucket(0xc000326180, 0xc000328360, 0x1, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0004eb770, 0xc0001ffea0, ...)   
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/minio/minio-go/v6/api-put-bucket.go:85 +0x24b
github.com/exoscale/cli/cmd.createBucket(...)
        /Users/marc/Documents/Exoscale/git/cli/cmd/sos_create.go:37
github.com/exoscale/cli/cmd.glob..func60(0x1547b00, 0xc000306210, 0x1, 0x3, 0x0, 0x0)
        /Users/marc/Documents/Exoscale/git/cli/cmd/sos_create.go:32 +0x1b3
github.com/spf13/cobra.(*Command).execute(0x1547b00, 0xc000306180, 0x3, 0x3, 0x1547b00, 0xc000306180)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/cobra/command.go:762 +0x465
github.com/spf13/cobra.(*Command).ExecuteC(0x1543d40, 0xde6728, 0xc000226fc0, 0xc00049bd80)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/cobra/command.go:800
github.com/exoscale/cli/cmd.Execute(0xf17458, 0x5, 0xf25530, 0x7)
        /Users/marc/Documents/Exoscale/git/cli/cmd/root.go:99 +0x1de
main.main()
        /Users/marc/Documents/Exoscale/git/cli/main.go:34 +0x6b

goroutine 19 [syscall]:
os/signal.signal_recv(0x0)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/sigqueue.go:139 +0x9c
os/signal.loop()
        /usr/local/Cellar/go/1.12.7/libexec/src/os/signal/signal_unix.go:23 +0x22
created by os/signal.init.0
        /usr/local/Cellar/go/1.12.7/libexec/src/os/signal/signal_unix.go:29 +0x41

goroutine 34 [select]:
github.com/exoscale/cli/cmd.Execute.func2(0xc000226fc0, 0xc00049bd80, 0xf52820, 0xc000301480)
        /Users/marc/Documents/Exoscale/git/cli/cmd/root.go:90 +0xb7
created by github.com/exoscale/cli/cmd.Execute
        /Users/marc/Documents/Exoscale/git/cli/cmd/root.go:89 +0x1a8

goroutine 6 [sleep]: 
runtime.goparkunlock(...)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/proc.go:307
time.Sleep(0x6790ba75f)
        /usr/local/Cellar/go/1.12.7/libexec/src/runtime/time.go:105 +0x159
github.com/minio/minio-go/v6.Client.newRetryTimer.func2(0xc000352a20, 0xa, 0xc0003529c0, 0xc0004eb8f0)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/minio/minio-go/v6/retry.go:82 +0x84
created by github.com/minio/minio-go/v6.Client.newRetryTimer
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/minio/minio-go/v6/retry.go:72 +0x156

real    0m27.487s
user    0m0.104s
sys     0m0.044s
```

**Comment by pierre-emmanuelJ** [comment]
Thanks for this issue, I will open a pull request ASAP

**Comment by falzm** [comment]
Thank you for reporting this bug. Good news: it doesn't actually *never* finish – it just takes a loooong while 🙃:

```console
$ time env ./exo sos create -z doesnotexist test
error: Put https://sos-doesnotexist.exo.io/test/: dial tcp: lookup sos-doesnotexist.exo.io: no such host

real	1m45.897s
user	0m0.076s
sys	0m0.026s
```

I'll implement a pre-flight check to ensure the zone specified actually exists before issuing the request.

**Comment by pierre-emmanuelJ** [comment]
We have to use more `context` to handle the  ^C in this case
