### ISSUE TITLE
exoscale-cli command panics when executed via sudo / as root

### ISSUE THREAD

**Issue by Daeinar** [exoscale/cli#270]
Hi Exoscale team,

When executing
```
sudo exo api security-group authorizeIngress --securitygroupid <id> --cidrlist 0.0.0.0/0 --startport 80 --endport 80 --protocol tcp
``` 
I'm getting the following panic:
```
panic: can not look up shorthand which is more than one ASCII character: "securitygroupid"

goroutine 1 [running]:
github.com/spf13/pflag.(*FlagSet).ShorthandLookup(0xc000740200, 0x7ffc97a8879c, 0xf, 0x1)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/pflag/flag.go:362 +0x1b3
github.com/exoscale/cli/cmd.getCmdPosition(0xeef04d, 0x6, 0xc00014c1a0)
        /Users/marc/Documents/Exoscale/git/cli/cmd/root.go:361 +0x299
github.com/exoscale/cli/cmd.isNonCredentialCmd(0xc0005af7f0, 0x3, 0x3, 0xc00026e2b0)
        /Users/marc/Documents/Exoscale/git/cli/cmd/root.go:332 +0x62
github.com/exoscale/cli/cmd.initConfig()
        /Users/marc/Documents/Exoscale/git/cli/cmd/root.go:242 +0x15a3
github.com/spf13/cobra.(*Command).preRun(0xc00013d8c0)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/cobra/command.go:872 +0x49
github.com/spf13/cobra.(*Command).execute(0xc00013d8c0, 0xc000530140, 0xa, 0xa, 0xc00013d8c0, 0xc000530140)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/cobra/command.go:808 +0x138
github.com/spf13/cobra.(*Command).ExecuteC(0x17943c0, 0xfe5048, 0xc00020c840, 0xc000235cd0)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/marc/Documents/Exoscale/git/cli/vendor/github.com/spf13/cobra/command.go:887
github.com/exoscale/cli/cmd.Execute(0x10ee36c, 0x6, 0x10fdf68, 0x7)
        /Users/marc/Documents/Exoscale/git/cli/cmd/root.go:104 +0x302
main.main()
        /Users/marc/Documents/Exoscale/git/cli/main.go:34 +0x6a
```
A similar issue was reported at https://github.com/google/keytransparency/issues/1295 and resolved via https://github.com/google/keytransparency/pull/1293.

Strangely when I execute the command without `sudo` everything works fine.

I'm using the following version: `exo 1.14.0 a84b0b6 (egoscale 0.26.6)`

**Comment by greut** [comment]
@Daeinar the issue at hand is that no configuration files were found by `exo`. Try the following:

```
sudo exo -C $HOME/.config/exoscale/exoscale.toml \
  api security-group authorizeIngress \
  --securitygroupid <id> \
  --cidrlist 0.0.0.0/0 \
  --startport 80 \
  --endport 80 \
  --protocol tcp
```

**Comment by greut** [comment]
if anyone wants to fix that, it's around there https://github.com/exoscale/cli/blob/master/cmd/root.go#L241-L248

**Comment by Daeinar** [comment]
@greut Great, providing the configuration file worked. Thanks a lot!

**Comment by pierre-emmanuelJ** [comment]
Thanks @greut! Thanks @Daeinar for reporting the issue. Yes you can use the configuration directly, we will fix the panic ASAP thank you.

**Comment by falzm** [comment]
Hi @Daeinar, in practice you should not resort to using `exo api` commands (those are really low-level and should only be used when there is no equivalent in the standard commands – and will soon be retired.

**Comment by Daeinar** [comment]
@falzm Thanks for the heads-up, that's good to know. Will use those commands instead in the future.

**Comment by greut** [comment]
\#wontfix
