### ISSUE TITLE
version 1.50 broke `exo compute instance show` command

### ISSUE THREAD

**Issue by mguegan** [exoscale/cli#437]
Since v1.50 I cannot get my instance details anymore:
```
./exo compute instance show <UUID> -z ch-dk-2

panic: reflect: NumField of non-struct type string

goroutine 1 [running]:
reflect.(*rtype).NumField(0x12372e0)
        reflect/type.go:1015 +0xb7
github.com/exoscale/cli/cmd.outputTableHeaders({0x1937f50, 0x12372e0})
        github.com/exoscale/cli/cmd/output.go:140 +0x4f
github.com/exoscale/cli/cmd.outputTable({0x12e6960, 0xc000614000})
        github.com/exoscale/cli/cmd/output.go:271 +0xc65
github.com/exoscale/cli/cmd.(*instanceShowOutput).toTable(0xc000614000)
        github.com/exoscale/cli/cmd/instance_show.go:34 +0x37
github.com/exoscale/cli/cmd.output({0x1905c88, 0xc000614000}, {0x0, 0x0})
        github.com/exoscale/cli/cmd/output.go:59 +0x9b
github.com/exoscale/cli/cmd.(*instanceShowCmd).cmdRun(0xc000507700, 0xc0000a8c80, {0xc00043a330, 0x1, 0x3})
        github.com/exoscale/cli/cmd/instance_show.go:163 +0xbe2
github.com/spf13/cobra.(*Command).execute(0xc0000a8c80, {0xc00043a300, 0x3, 0x3})
        github.com/spf13/cobra@v1.1.3/command.go:852 +0x8dc
github.com/spf13/cobra.(*Command).ExecuteC(0x2091000)
        github.com/spf13/cobra@v1.1.3/command.go:960 +0x525
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.1.3/command.go:897
github.com/exoscale/cli/cmd.Execute({0x18df83c, 0x6}, {0x18e0200, 0x8})
        github.com/exoscale/cli/cmd/root.go:102 +0x225
main.main()
        github.com/exoscale/cli/main.go:34 +0x6a
```
Culprit seems to be [there](https://github.com/exoscale/cli/compare/v1.49.3...v1.50.0#diff-63e01a66dd302c4dcf6ca7738b1ca37b4e760e700e32bf1701ab278f4e6801c0R140)

But that needs confirmation.

Confirmed OK with `1.49.3`

**Comment by 7fELF** [comment]
Hi @mguegan,

Thanks for the report!
Your issue will be fixed soon with PR #439

[sc43900]
