### ISSUE TITLE
[Bug]: "exo storage presign help" crashes

### ISSUE THREAD

**Issue by udf2457** [exoscale/cli#588]
### Current Behavior

```
exo storage presign help
panic: runtime error: index out of range [1] with length 1

goroutine 1 [running]:
github.com/exoscale/cli/cmd.init.func65(0x104afd4e0, {0x1400064e5c0, 0x1, 0x1035d0e37?})
	github.com/exoscale/cli/cmd/storage_presign.go:44 +0x35c
github.com/spf13/cobra.(*Command).execute(0x104afd4e0, {0x1400064e4c0, 0x1, 0x1})
	github.com/spf13/cobra@v1.3.0/command.go:856 +0x568
github.com/spf13/cobra.(*Command).ExecuteC(0x104af93e0)
	github.com/spf13/cobra@v1.3.0/command.go:974 +0x318
github.com/spf13/cobra.(*Command).Execute(...)
	github.com/spf13/cobra@v1.3.0/command.go:902
github.com/exoscale/cli/cmd.Execute({0x103dd8210?, 0x1027406c0?}, {0x103dd8828?, 0x140000021c0?})
	github.com/exoscale/cli/cmd/root.go:81 +0x1c4
main.main()
	github.com/exoscale/cli/main.go:34 +0x58
```

### CLI Version

exo 1.77.0 07b0d73f (egoscale 0.102.3)

### Os platform

OS X 14.4.1

**Comment by sauterp** [comment]
thank you kindly for reporting this, a fix is on the way!
